### ISSUE TITLE
Serve via github pages

### ISSUE THREAD

**Issue by yaxu** [yaxu/lighthouse#5]

**Comment by stretchyboy** [comment]
Have you done this before? Because I could do that once holger's changes
are up.

On 17 January 2016 at 08:24, Alex McLean notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/yaxu/lighthouse/issues/5.

## 

Regards,

## Martyn

https://twitter.com/#!/stretchyboy

**Comment by yaxu** [comment]
Super, the changes are already up

**Comment by stretchyboy** [comment]
Shall we have the actual thing on the front page or an index.html that explains it first ?

**Comment by yaxu** [comment]
We could have the thing with a bit of explanation underneath?

On 17 January 2016 at 09:46, Martyn Eggleton notifications@github.com
wrote:

> Shall we have the actual thing on the front page or an index.html that
> explains it first ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yaxu/lighthouse/issues/5#issuecomment-172306438.

## 

http://yaxu.org/

**Comment by stretchyboy** [comment]
Ok, that means moving it to the root of the project but not a problem at all.

**Comment by stretchyboy** [comment]
OK , Fixed (although I haven't added any text etc. so it just plays).
It is at http://yaxu.github.io/lighthouse/
The procedure is to get the changes you want working in the master branch, then 
either

```
git push origin gh-pages
```

which i think will work or

``` bash
git checkout gh-pages
git pull origin master   # it will often get you to commit the merge now if not fix issues and commit
git push origin gh-pages
git checkout master
```
